# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    '''
    Creates an index for fuzzy search
    '''

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
            migrations.RunSQL(
            'CREATE INDEX trgm_idx ON calories_food USING gin (name gin_trgm_ops);'
            )
    ]
