version: '2'
services:
    backend:
        build: ./backend/.
        image: banjocat/calorie_find:latest
        depends_on:
            - db
        command: bash -c "/tmp/wait-for-it.sh -h db -p 5432 && ./manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend/calorie_find:/opt/api
        ports: 
            - "8000:8000"
    db:
        image: postgres:9
        environment:
            - POSTGRES_USER=food
            - POSTGRES_PASSWORD=food

