
version: '2'
services:
    backend:
        image: banjocat/calorie_find:latest
        container_name: food_backend
        depends_on:
            - db
            - fixture
        command: bash -c "/tmp/wait-for-it.sh -h db -p 5432 && python ./manage.py runserver 0.0.0.0:8000"
        environment:
            - debug=yes
        ports:
            - "8020:8000"
    db:
        image: banjocat/calorie_find_db:latest
        container_name: calorie_find_db
        environment:
            - POSTGRES_USER=food
            - POSTGRES_PASSWORD=food
    fixture:
        image: banjocat/calorie_find:latest
        container_name: calorie_find_db_fixture
        depends_on:
            - db
        command: |
            bash -c "\
            /tmp/wait-for-it.sh -h db -p 5432 && \
            ./manage.py makemigrations && \
            ./manage.py migrate && \
            ./manage.py loaddata calories/fixtures/food.json && \
            echo Database migrations done!!"


