---

- name: Login into dockerhub
  docker_login:
      username: "{{docker_user}}"
      password: "{{docker_password}}"
      email: "{{docker_email}}"
  tags:
      - deploy

- name: Add tmp directory
  file:
      path: /tmp/food_calorie
      state: directory
  tags:
      - deploy

- name: Add compose
  template:
      src: ./templates/docker-compose.yml
      dest: /tmp/food_calorie/docker-compose.yml
  tags:
      - deploy




- name: Run staging compose
  docker_service:
      build: yes
      project_src: /tmp/food_calorie/
  tags:
      - deploy


