---

- name: Login into dockerhub
  docker_login:
      username: "{{docker_user}}"
      password: "{{docker_password}}"
      email: "{{docker_email}}"
  tags:
      - deploy


- name: Add compose
  copy:
      src: ./files/docker-compose.yml
      dest: /tmp/.
  tags:
      - deploy


- name: Run staging compose
  docker_service:
      build: true
      recreate: smart
      project_src: /tmp/.
  tags:
      - deploy
