---


- name: Add tmp directory
  file:
      path: /tmp/food_calorie
      state: directory
  tags:
      - deploy


- name: Add compose
  template:
      src: ./templates/docker-compose.yml
      dest: /tmp/food_calorie/docker-compose.yml
  tags:
      - deploy


- name: Pull images
  shell: docker-compose -f /tmp/food_calorie/docker-compose.yml pull
  tags:
      - deploy


- name: Run staging compose
  docker_service:
      project_src: /tmp/food_calorie/
  tags:
      - deploy


