---


- name: Add tmp directory
  file:
      path: /tmp/food_calorie
      state: directory
  tags:
      - deploy

- name: Add compose
  template:
      src: ./templates/docker-compose.yml
      dest: /tmp/food_calorie/docker-compose.yml
  tags:
      - deploy


- name: Bring down compose until ansible 2.2 for pull
  docker_service:
      state: absent
      project_src: /tmp/food_calorie/
  tags:
      - deploy

- name: Run staging compose
  docker_service:
      build: yes
      project_src: /tmp/food_calorie/
  tags:
      - deploy


